export type Paginated<T> = {
    data: T[];
    links: { url: string | null; label: string; active: boolean }[];
    meta?: unknown;
};

export type Category = {
    id: number;
    name: string;
    slug: string;
    description?: string;
    is_active?: boolean;
    jobs_count?: number;
};
export type Location = {
    id: number;
    name: string;
    slug: string;
    country?: string;
    is_active?: boolean;
    jobs_count?: number;
};
export type Skill = { id: number; name: string; slug: string };
export type Company = {
    id: number;
    name: string;
    slug: string;
    logo?: string | null;
    cover_image?: string | null;
    industry?: string;
    company_size?: number;
    website?: string;
    phone?: string;
    email?: string;
    address?: string;
    description?: string;
    verification_status: 'pending' | 'approved' | 'rejected';
    moderation_note?: string;
    is_active: boolean;
    jobs_count?: number;
    rating_avg?: number;
    reviews_count?: number;
    verification_documents?: { id: number; document_type: string; file_path: string; status: string; note?: string }[];
    user?: { id: number; name: string; email: string };
};
export type Job = {
    id: number;
    title: string;
    slug: string;
    description: string;
    responsibilities?: string;
    requirements?: string;
    benefits?: string;
    salary_min?: number;
    salary_max?: number;
    salary_currency: string;
    job_type: string;
    work_mode?: string;
    experience_level: string;
    deadline: string;
    status: string;
    moderation_note?: string;
    is_featured: boolean;
    is_urgent?: boolean;
    views_count?: number;
    match_score?: number;
    match_reasons?: string[];
    applications_count?: number;
    company?: Company;
    category?: Category;
    location?: Location;
    skills?: Skill[];
};
export type Application = {
    id: number;
    status: string;
    cover_letter?: string;
    cv_file?: string;
    user?: any;
    job?: Job;
    status_updates?: any[];
};
